### PR TITLE
Pickpocket gloves strip refactor and other madness [WIP]

### PR DESCRIPTION
**Pull request by X-TheDark**
Hello, it's nice to see you interested in reading through all of this, so, let's get things rolling.
#### Why?

This Module Framework will allow any obj/item to hold modules, provided you define a module_holder for it. For the most part, all changes are in their own files in code/modules/modular.

This would allow a (hopefully) expandable system of modules that can apply effects if they are in your equipment. Some examples:
1. Having a "Reactive Teleport" module that you can insert into any clothing, so it acts like RD's Reactive Teleport Armor instead of being hardcoded to one subtype;
2. Having a "Shoot generic laser" (name subject to change) in your gloves that does what you'd expect it to do based on the name it was given;
3. Having equipment modules "Health Scanner Module"/etc that can be put into Gloves for doctors so you can click on people and not need the medical scanner in your hand.
4. Having a module that grants some sort of ability/spell/whatever.
#### How?

Framework consists of the following key objects:
- `obj/module_holder` - object that holds the modules and communicates with them, based on a associated list of ("id" = module_object);
- `obj/item/module` - the module that you can hit items with that will be put into it, if possible;

This is planned to be resolved in 5 ways:
1. Clicks on things without anything in your hand when they are adjacent;
2. Click on things without anything in your hand when they are not adjacent;
3. Clicks while weapon in hand on adjacent targets;
4. Clicks while weapon in hand on non-adjacent targets;
5. Being hit (hit_reaction, basically);

Resolution is done using `/datum/resolution_order` thing that has a few subtypes. This datum describes which slots are allowed and the order. By default, you cannot insert the same slot more than once into it (controlled by a var).

Default resolution rules:
1. Unarmed/Ranged attacks (aka clicks for when you don't have anything in your hand) resolve modules for Head->Mask->Suit->Uniform->Gloves, in that order.
2. Attacks (with an object) only resolve the hand that the object is currently held.
#### Resolution?

So, what exactly is a resolution, when talking about modules and holders?

Resolution is based on slots (`slot_r_hand`, `slot_wear_mask`, etc). In the resolution datum, you pass it the slot defines that it then adds to it's order. You can pass it a single variable or a list of them. When trying to add it, it compares the values to the allowed one (defined in `list/allowed` in the datum)
#### Task List
- [ ] ~~Add a way to add/remove module_holders~~ (Not planned until I work out and test the system live)
- [x] Add interaction rules to equipment to allow removal/addition of modules (only for a type of gloves currently)
- [x] Add a way to interact with modules that's not awful (Verb+Topic, maybe Action Button, but don't count on it on the first pass);
- [X] Create the module_holder and module objects and add module_holder as a var to obj/item
- [X] Define resolution proc for mobs (since it's based on what they are wearing)
- [X] Define Unarmed/Ranged attack resolution rules;
- [X] Define object Melee attack resolution rules;
- [x] Define object Ranged attack resolution rules;
- [x] Define on hit resolution rules;
- [x] Hook aforementioned resolution rules into module_holder and modules;
#### Admin-only modules
- [x] Shock Module for Gloves (idea stolen from goonstation - Poweglove);
- [ ] Stun Module for Gloves (STUNGLOVES COMING BACK 2016);
- [ ] ~~Laser Module for any clothing~~ Moved to Advanced Features. I want to finish this and roll this out as soon as possible, before this becomes unmanageable for me to continue implementing;
- [ ] ~~Blink Module for clothing - gives you the Blink spell from Wizard, basically. Both on hit and an actual ability you can use;~~ Cancelled for the first (Basic) implementation, too advanced, as the spell system doesn't support this kind of thing...at all.
- [X] etc
#### Something, something, pickpocket module
- [ ] Create it
- [ ] Actually make it do stuff
- [ ] Improve it

### CODE REVIEW

**Comment by Ephemeralis** [comment]
Excellent idea. We should set up projects for refactoring other big systems, too.

**Comment by X-TheDark** [comment]
My biggest concern with this is performance, as I'm adding about a dozen of procs to be called on each click of the client...which I'm not a big fan of.

**Comment by X-TheDark** [comment]
In this commit - more groundwork. Hopefully, I'm actually done with the hooking of clicks on stuff...defense modules is a assoc list split into 2 parts global/local modules. Thanks @Ephemeralis for the suggestions provided.

Now to work on being clicked on by others...

**Comment by X-TheDark** [comment]
In this commit - finally done with the hooking procs. Modules now how 4 new procs:
* on_attack_hand
* on_attack_by
* on_bullet_act
* on_hitby

The names should be self-evident as to what they hook to...also tightens some checks, adds a new defense module resolution proc and the order datums.

**Pull request closed without merging**
